### ISSUE TITLE
[BUG] CTRL + A on AZERTY = CTRL + Q

### ISSUE THREAD

**Issue by farvardin** [ace-dent/picotracker#6]
**Describe the bug / feature**
the AZERTY  keymap is working for typing some code. A = A for instance. But there is a bug in CTRL + A which is understood in SDL as CTRL+Q instead (like on qwerty keyboard).

**Software (please complete the following information):**
 - OS: Linux Mint 21.3
 - Version:  v0.1.0b

**Comment by ace-dent** [comment]
@farvardin please can you re-test with latest release?

**Comment by OniriCorpe** [comment]
seems solved using v0.1.0e

**Comment by ace-dent** [comment]
Thanks @OniriCorpe. 👍🏻 
Closing based on comment.
